//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU
    {
        public int SKUId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> WholesalePrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<System.DateTime> RecordLastUpdate { get; set; }
        public Nullable<System.DateTime> RecordStartDate { get; set; }
        public Nullable<System.DateTime> RecordEndDate { get; set; }
        public string Deleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
